# Generated by Django 2.2.6 on 2019-10-30 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dyasynora_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='name',
            new_name='activity_name',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='creator',
            new_name='project_creator',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='description',
            new_name='project_description',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='name',
            new_name='project_name',
        ),
        migrations.AlterField(
            model_name='activity',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
