# Generated by Django 2.2.6 on 2019-11-05 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dyasynora_app', '0003_auto_20191103_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_img',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to=''),
        ),
    ]
