# Generated by Django 2.2.6 on 2019-11-10 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dyasynora_app', '0005_project_project_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_creator',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_img',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_cost',
        ),
    ]
