# Generated by Django 2.2.6 on 2019-11-10 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dyasynora_app', '0006_auto_20191110_0032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='img',
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='project_pics'),
        ),
    ]
