# Generated by Django 2.2.6 on 2019-11-11 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dyasynora_app', '0007_auto_20191110_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(default='default_proj.jpg', upload_to='project_pics'),
        ),
    ]
