# Generated by Django 2.2.6 on 2019-11-16 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dyasynora_app', '0009_auto_20191116_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='stage',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
