# Generated by Django 2.2.6 on 2019-12-20 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dyasynora_app', '0012_auto_20191220_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
