# Generated by Django 2.2.6 on 2019-12-20 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dyasynora_app', '0013_auto_20191220_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='org',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
