# Generated by Django 2.2.6 on 2019-12-20 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dyasynora_app', '0014_project_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='org_desc',
            field=models.TextField(default='default description'),
            preserve_default=False,
        ),
    ]
