# Generated by Django 3.0.6 on 2020-06-06 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dyasynora_app', '0017_project_description_customisable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='name',
        ),
    ]
