# Generated by Django 3.0.6 on 2020-06-06 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dyasynora_app', '0018_remove_project_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='name',
            field=models.CharField(default='hey', max_length=29),
            preserve_default=False,
        ),
    ]
