# Generated by Django 3.0.6 on 2020-06-06 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dyasynora_app', '0021_project_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsor_datetime', models.DateTimeField(verbose_name='%d/%m/%Y %H:%M:%S')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dyasynora_app.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(verbose_name='%d/%m/%Y %H:%M:%S')),
                ('end_datetime', models.DateTimeField(verbose_name='%d/%m/%Y %H:%M:%S')),
                ('message', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dyasynora_app.Project')),
                ('volunteer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opportunity_datetime', models.DateTimeField(verbose_name='%d/%m/%Y %H:%M:%S')),
                ('description', models.TextField()),
                ('message', models.TextField()),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dyasynora_app.Project')),
            ],
        ),
        migrations.RemoveField(
            model_name='sponsor',
            name='project',
        ),
        migrations.RemoveField(
            model_name='sponsor',
            name='sponsor',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='volunteer',
        ),
        migrations.DeleteModel(
            name='Mentor',
        ),
        migrations.DeleteModel(
            name='Sponsor',
        ),
        migrations.DeleteModel(
            name='Volunteer',
        ),
    ]
