# Generated by Django 3.0.6 on 2020-06-09 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dyasynora_app', '0026_auto_20200609_1744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='description_customisable',
            new_name='story',
        ),
    ]
