# Generated by Django 3.0.6 on 2020-06-09 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dyasynora_app', '0028_auto_20200609_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='sponsor_datetime',
        ),
        migrations.AddField(
            model_name='campaign',
            name='campaign_end',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='%d/%m/%Y'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='campaign_start',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='%d/%m/%Y'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='organiser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dyasynora_app.Project'),
        ),
        migrations.AlterField(
            model_name='event',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='opportunity_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='%d/%m/%Y %H:%M:%S'),
        ),
    ]
