# Generated by Django 3.0.6 on 2020-06-26 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dyasynora_app', '0033_event_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='title',
            field=models.CharField(default='title', max_length=50),
            preserve_default=False,
        ),
    ]
