# Generated by Django 3.0.6 on 2020-06-26 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dyasynora_app', '0034_opportunity_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='image',
            field=models.ImageField(default='default_proj.jpg', upload_to='opportunity_pics'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='image',
            field=models.ImageField(default='default_proj.jpg', upload_to='campaign_pics'),
        ),
    ]
