# Generated by Django 3.0.6 on 2020-06-26 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dyasynora_app', '0035_auto_20200626_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(default='default_proj.jpg', upload_to='event_pics'),
        ),
    ]
